from arm32v7/python:3.7.0-slim-stretch

COPY /isitworking_app /app/
WORKDIR /app
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt

ENTRYPOINT gunicorn -w 2 -b 0.0.0.0:5000 isitworking:app
